import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from 'next/image';
import Link from "next/link";
import ReactPlayer from "react-player";
import { api } from "~/utils/api";
import tvFrame from '../../public/assets/tv_frame.jpg';


export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center">
        <div className="bg-[url('../../public/assets/tv_frame.jpg')] bg-contain bg-no-repeat bg-center p-[2.7rem] sm:p-20">
          <div className="flex justify-center items-center max-w-xl">
            <ReactPlayer
              controls
              height="100%"
              url="https://dx19ntdwg65hl.cloudfront.net/tape_1_12_3_91_school_show0526-111805.mp4"
              width="100%"
            />
          </div>
        </div>
        <div className="bg-cyan-400 h-9 w-4/5 max-w-xl" />
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
